// Generated by CoffeeScript 2.3.2
(function() {
  /**
   * Copyright 2018, Wilfred Springer
   *
   * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
   * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
   *
   * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   * SOFTWARE.
   */
  module.exports = function(regex) {
    return {
      match: function(str) {
        var forEach, map, re, reduce;
        
        // We want to be able to iterate over matches over and over again.
        re = new RegExp(regex);
        reduce = function(step, initial) {
          var acc, m;
          acc = initial;
          while ((m = regex.exec(str)) != null) {
            if (m.index === regex.lastIndex) {
              regex.lastIndex += 1;
            }
            acc = step(acc, m);
          }
          return acc;
        };
        map = function(mapfn) {
          return reduce((function(acc, m) {
            acc.push(mapfn(m));
            return acc;
          }), []);
        };
        forEach = function(it) {
          return reduce(function(acc, m) {
            return it(m);
          });
        };
        return {reduce, map, forEach};
      }
    };
  };

}).call(this);
